"""
Abstract base class for trading strategies.

All strategies must implement this interface. The bot's signal generator
calls `analyze()` on each new candle to check for trade signals.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional, Any

import pandas as pd


@dataclass
class Signal:
    """A trading signal generated by a strategy."""

    timestamp: str
    instrument: str
    direction: str          # "LONG" or "SHORT"
    strategy: str           # Strategy name
    entry_price: float      # Recommended entry price
    stop_loss: float        # Stop loss price
    take_profit: float      # Take profit price
    confidence: float       # Signal confidence (0.0 - 1.0)

    # Strategy-specific metadata
    fib_levels: dict[float, float] = field(default_factory=dict)
    vwap_value: float = 0.0
    triggered_level: float = 0.0     # Which fib ratio triggered
    trend_direction: str = ""         # "UP" or "DOWN"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for PocketBase storage."""
        return {
            "timestamp": self.timestamp,
            "instrument": self.instrument,
            "direction": self.direction,
            "strategy": self.strategy,
            "entry_price": self.entry_price,
            "fib_levels": self.fib_levels,
            "vwap_value": self.vwap_value,
            "confidence": self.confidence,
            "triggered_level": self.triggered_level,
            "trend_direction": self.trend_direction,
        }

    def signal_metadata(self) -> dict[str, Any]:
        """Metadata to store alongside the trade record."""
        return {
            "fib_levels": {str(k): v for k, v in self.fib_levels.items()},
            "vwap_value": self.vwap_value,
            "triggered_level": self.triggered_level,
            "trend_direction": self.trend_direction,
            "confidence": self.confidence,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
        }


class Strategy(ABC):
    """Abstract base class for all trading strategies."""

    @abstractmethod
    def name(self) -> str:
        """Return the strategy identifier name."""
        ...

    @abstractmethod
    def display_name(self) -> str:
        """Return a human-readable strategy name."""
        ...

    @abstractmethod
    def analyze(self, df: pd.DataFrame) -> Optional[Signal]:
        """
        Analyze market data and optionally generate a trading signal.

        Args:
            df: DataFrame with OHLCV columns and DatetimeIndex

        Returns:
            A Signal object if conditions are met, otherwise None
        """
        ...

    @abstractmethod
    def get_default_params(self) -> dict:
        """Return default strategy parameters."""
        ...
